#!/usr/bin/env bash
# Detect hardware capabilities: GPU, CUDA, RAM, CPU, OS
# Outputs to ~/.machine_setting_profile (sourced by other scripts)
set -euo pipefail

PROFILE="${1:-$HOME/.machine_setting_profile}"

echo "=== Hardware Detection ==="

# --- GPU Detection ---
HAS_GPU=false
GPU_NAME=""
GPU_COUNT=0
CUDA_VERSION=""
CUDA_SUFFIX="cpu"

if command -v lspci &>/dev/null; then
    GPU_INFO=$(lspci 2>/dev/null | grep -i 'vga\|3d\|display' | grep -i nvidia || true)
    if [ -n "$GPU_INFO" ]; then
        HAS_GPU=true
        GPU_COUNT=$(echo "$GPU_INFO" | wc -l)
        # Try to get GPU name from nvidia-smi
        if command -v nvidia-smi &>/dev/null; then
            GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "Unknown NVIDIA GPU")
        else
            GPU_NAME=$(echo "$GPU_INFO" | head -1 | sed 's/.*: //')
        fi
    fi
fi

# --- CUDA Detection ---
if [ "$HAS_GPU" = true ]; then
    if command -v nvcc &>/dev/null; then
        CUDA_VERSION=$(nvcc --version 2>/dev/null | grep -oP 'release \K[0-9]+\.[0-9]+' || true)
    elif [ -f /usr/local/cuda/version.txt ]; then
        CUDA_VERSION=$(grep -oP '[0-9]+\.[0-9]+' /usr/local/cuda/version.txt | head -1)
    elif command -v nvidia-smi &>/dev/null; then
        CUDA_VERSION=$(nvidia-smi 2>/dev/null | grep -oP 'CUDA Version: \K[0-9]+\.[0-9]+' || true)
    fi

    if [ -n "$CUDA_VERSION" ]; then
        # Convert 13.0 → cu130, 12.4 → cu124
        CUDA_SUFFIX="cu$(echo "$CUDA_VERSION" | tr -d '.')"
    fi
fi

# --- System Info ---
OS_NAME=$(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME" || uname -s)
OS_ID=$(. /etc/os-release 2>/dev/null && echo "$ID" || echo "unknown")
ARCH=$(uname -m)
RAM_GB=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo "unknown")
CPU_MODEL=$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | sed 's/.*: //' || echo "unknown")
CPU_CORES=$(nproc 2>/dev/null || echo "unknown")

# --- Profile Suggestion ---
if [ "$HAS_GPU" = true ] && [ "$RAM_GB" -ge 16 ] 2>/dev/null; then
    SUGGESTED_PROFILE="gpu-workstation"
elif [ "$HAS_GPU" = true ]; then
    SUGGESTED_PROFILE="gpu-workstation"
elif [ "$RAM_GB" -ge 32 ] 2>/dev/null; then
    SUGGESTED_PROFILE="cpu-server"
elif [ "$RAM_GB" -ge 8 ] 2>/dev/null; then
    SUGGESTED_PROFILE="laptop"
else
    SUGGESTED_PROFILE="minimal"
fi

# --- Output ---
echo "  GPU: ${HAS_GPU} (${GPU_COUNT}x ${GPU_NAME:-none})"
echo "  CUDA: ${CUDA_VERSION:-none} (${CUDA_SUFFIX})"
echo "  CPU: ${CPU_MODEL} (${CPU_CORES} cores)"
echo "  RAM: ${RAM_GB}GB"
echo "  OS: ${OS_NAME} (${ARCH})"
echo "  Profile: ${SUGGESTED_PROFILE}"

# --- Write profile ---
cat > "$PROFILE" << EOF
# Auto-generated by detect-hardware.sh on $(date -I)
# Do NOT commit this file
HAS_GPU=${HAS_GPU}
GPU_NAME="${GPU_NAME}"
GPU_COUNT=${GPU_COUNT}
CUDA_VERSION="${CUDA_VERSION}"
CUDA_SUFFIX="${CUDA_SUFFIX}"
OS_NAME="${OS_NAME}"
OS_ID="${OS_ID}"
ARCH="${ARCH}"
RAM_GB=${RAM_GB}
CPU_MODEL="${CPU_MODEL}"
CPU_CORES=${CPU_CORES}
SUGGESTED_PROFILE="${SUGGESTED_PROFILE}"
EOF

echo ""
echo "Profile saved to: $PROFILE"
