#!/usr/bin/env bash
# Export current venv packages → categorized requirements files
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PKG_DIR="$REPO_DIR/packages"

# Detect active venv or use default
VENV_PATH="${VIRTUAL_ENV:-$HOME/ai-env}"
PIP="$VENV_PATH/bin/pip"

if [ ! -x "$PIP" ]; then
    echo "Error: No pip found at $PIP"
    echo "Activate a venv first or ensure ~/ai-env exists."
    exit 1
fi

echo "Exporting packages from: $VENV_PATH"

# Get current freeze
FREEZE=$("$VENV_PATH/bin/uv" pip freeze 2>/dev/null || "$PIP" freeze)

# === Category patterns ===
# GPU packages (nvidia-*, cuda-*, torch+cu*, triton, bitsandbytes)
GPU_PATTERNS='nvidia-|cuda-|torch==.*\+cu|torchaudio==.*\+cu|torchvision==.*\+cu|triton==|bitsandbytes==|onnxruntime-gpu=='

# Data packages
DATA_PATTERNS='pandas==|pyarrow==|SQLAlchemy==|alembic==|psycopg2|PyMySQL==|oracledb==|cx-Oracle==|clickhouse-|pdfplumber==|pdfminer|pypdf==|pypdfium2==|python-docx==|python-pptx==|openpyxl==|xlsxwriter==|lxml==|pillow==|opencv-|scikit-image==|ImageIO==|easyocr==|pytesseract==|orjson==|ormsgpack==|jsonlines==|aiokafka==|kafka-python==|paho-mqtt==|boto3==|botocore==|s3transfer=='

# Web packages
WEB_PATTERNS='fastapi==|starlette==|uvicorn==|uvloop==|Flask==|Werkzeug==|gradio|httpx|httpcore==|requests==|requests-oauthlib==|requests-toolbelt==|urllib3==|aiohttp==|h11==|httptools==|websockets==|websocket-client==|watchfiles==|python-multipart==|Jinja2==|MarkupSafe==|itsdangerous==|PyJWT==|bcrypt==|cryptography==|pyOpenSSL==|prometheus_client==|sentry-sdk=='

# System packages to exclude (Ubuntu system packages, not pip-installed)
EXCLUDE_PATTERNS='bcc==|cloud-init==|command-not-found==|configobj==|dbus-python==|distro-info==|gpg==|launchpadlib==|lazr\.|netifaces==|PyGObject==|PyHamcrest==|python-apt==|python-debian==|screen-resolution-extra==|service-identity==|sos==|ssh-import-id==|systemd-python==|Twisted==|ubuntu-|ufw==|unattended-upgrades==|xkit==|Automat==|constantly==|hyperlink==|incremental==|zope\.|Babel==|blinker==|netaddr=='

# Filter function
categorize() {
    local pattern="$1"
    echo "$FREEZE" | grep -P "$pattern" || true
}

# Exclude system packages from freeze
CLEAN_FREEZE=$(echo "$FREEZE" | grep -Pv "$EXCLUDE_PATTERNS" || true)

# Extract categories
GPU_PKGS=$(echo "$CLEAN_FREEZE" | grep -P "$GPU_PATTERNS" || true)
DATA_PKGS=$(echo "$CLEAN_FREEZE" | grep -P "$DATA_PATTERNS" || true)
WEB_PKGS=$(echo "$CLEAN_FREEZE" | grep -P "$WEB_PATTERNS" || true)

# Core = everything else (minus GPU, data, web)
CORE_PKGS=$(echo "$CLEAN_FREEZE" | grep -Pv "$GPU_PATTERNS" | grep -Pv "$DATA_PATTERNS" | grep -Pv "$WEB_PATTERNS" || true)

# Write files with headers
write_req() {
    local file="$1"
    local header="$2"
    local content="$3"
    echo "# $header" > "$file"
    echo "# Auto-generated by export-packages.sh on $(date -I)" >> "$file"
    echo "" >> "$file"
    echo "$content" >> "$file"
}

write_req "$PKG_DIR/requirements-gpu.txt" "GPU-specific packages (NVIDIA CUDA)" "$GPU_PKGS"
write_req "$PKG_DIR/requirements-data.txt" "Data processing, databases, and file format packages" "$DATA_PKGS"
write_req "$PKG_DIR/requirements-web.txt" "Web frameworks, API, and HTTP packages" "$WEB_PKGS"
write_req "$PKG_DIR/requirements-core.txt" "Core AI/ML packages (platform-independent)" "$CORE_PKGS"

# CPU file is manually maintained (not auto-exported)
echo ""
echo "Exported packages:"
echo "  core: $(echo "$CORE_PKGS" | grep -c '==' || echo 0) packages"
echo "  gpu:  $(echo "$GPU_PKGS" | grep -c '==' || echo 0) packages"
echo "  data: $(echo "$DATA_PKGS" | grep -c '==' || echo 0) packages"
echo "  web:  $(echo "$WEB_PKGS" | grep -c '==' || echo 0) packages"
echo "  cpu:  (manually maintained)"
echo ""
echo "Total: $(echo "$CLEAN_FREEZE" | grep -c '==' || echo 0) packages"
echo "Excluded system packages: $(echo "$FREEZE" | grep -Pc "$EXCLUDE_PATTERNS" || echo 0)"
