#!/usr/bin/env bash
# lib-checkpoint.sh — Checkpoint/Rollback Library for setup.sh
# Source this file; do not execute directly.
# Provides: state tracking, rollback, backup, resume menu.

# --- Constants ---
CHECKPOINT_DIR="$HOME/.machine_setting"
CHECKPOINT_STATE="$CHECKPOINT_DIR/install.state"
CHECKPOINT_BACKUP_DIR="$CHECKPOINT_DIR/backups"

# --- State file helpers ---

# Initialize checkpoint directory and state file.
# Call once at setup.sh start.
checkpoint_init() {
    mkdir -p "$CHECKPOINT_DIR" "$CHECKPOINT_BACKUP_DIR"
    if [ ! -f "$CHECKPOINT_STATE" ]; then
        cat > "$CHECKPOINT_STATE" <<EOF
# Auto-generated by machine_setting installer
INSTALL_STARTED="$(date -u +%Y-%m-%dT%H:%M:%S)"
STAGE_1_HARDWARE=pending
STAGE_2_NVIDIA=pending
STAGE_3_PYTHON=pending
STAGE_4_VENV=pending
STAGE_5_NODE=pending
STAGE_6_JAVA=pending
STAGE_7_SHELL=pending
STAGE_4_GROUPS_DONE=""
VENV_PATH=""
PYTHON_VERSION=""
EOF
    fi
}

# Read a value from state file.
# Usage: val=$(checkpoint_read_key "STAGE_1_HARDWARE")
checkpoint_read_key() {
    local key="$1"
    if [ -f "$CHECKPOINT_STATE" ]; then
        grep "^${key}=" "$CHECKPOINT_STATE" 2>/dev/null | head -1 | cut -d'=' -f2- | tr -d '"'
    fi
}

# Write/update a key in the state file.
# Usage: checkpoint_write_key "STAGE_1_HARDWARE" "done"
checkpoint_write_key() {
    local key="$1" value="$2"
    if [ -f "$CHECKPOINT_STATE" ] && grep -q "^${key}=" "$CHECKPOINT_STATE" 2>/dev/null; then
        # Update existing key (portable sed -i)
        local tmp
        tmp=$(mktemp)
        sed "s|^${key}=.*|${key}=\"${value}\"|" "$CHECKPOINT_STATE" > "$tmp"
        mv "$tmp" "$CHECKPOINT_STATE"
    else
        echo "${key}=\"${value}\"" >> "$CHECKPOINT_STATE"
    fi
}

# --- Stage lifecycle ---

# Record stage start. Sets state to in_progress.
checkpoint_start_stage() {
    local n="$1" name="$2"
    checkpoint_write_key "STAGE_${n}_${name}" "in_progress"
}

# Record stage completion. Sets state to done.
checkpoint_complete_stage() {
    local n="$1" name="$2"
    checkpoint_write_key "STAGE_${n}_${name}" "done"
}

# Record stage failure, trigger rollback.
checkpoint_fail_stage() {
    local n="$1" name="$2"
    checkpoint_write_key "STAGE_${n}_${name}" "failed"
    echo ""
    echo "  [FAIL] Stage $n ($name) failed. Running rollback..."
    rollback_stage "$n"
}

# Get stage state: done | failed | pending | in_progress | skipped
checkpoint_get_state() {
    local n="$1" name="$2"
    checkpoint_read_key "STAGE_${n}_${name}"
}

# Returns 0 (true) if stage is done or was skipped.
checkpoint_is_done() {
    local n="$1" name="$2"
    local state
    state=$(checkpoint_get_state "$n" "$name")
    [ "$state" = "done" ] || [ "$state" = "skipped" ]
}

# --- Venv package group sub-tracking ---

# Record a completed package group for stage 4 (venv).
checkpoint_add_group_done() {
    local group="$1"
    local current
    current=$(checkpoint_read_key "STAGE_4_GROUPS_DONE")
    # Avoid duplicates
    if ! echo " $current " | grep -q " $group "; then
        checkpoint_write_key "STAGE_4_GROUPS_DONE" "${current:+$current }$group"
    fi
}

# Check if a package group is already done.
checkpoint_is_group_done() {
    local group="$1"
    local current
    current=$(checkpoint_read_key "STAGE_4_GROUPS_DONE")
    echo " $current " | grep -q " $group "
}

# --- Metadata ---

# Save venv path and python version to state for doctor/uninstall use.
checkpoint_save_metadata() {
    local venv_path="$1" python_version="$2"
    checkpoint_write_key "VENV_PATH" "$venv_path"
    checkpoint_write_key "PYTHON_VERSION" "$python_version"
}

# --- Rollback ---

# Per-stage rollback actions.
rollback_stage() {
    local n="$1"
    case "$n" in
        1)
            echo "  [Rollback] Removing hardware profile..."
            rm -f "$HOME/.machine_setting_profile"
            ;;
        2)
            echo "  [Rollback] NVIDIA rollback — manual cleanup may be needed"
            echo "  Run: ./scripts/install-nvidia.sh --uninstall"
            ;;
        3)
            echo "  [Rollback] Uninstalling managed Python..."
            local pyver
            pyver=$(checkpoint_read_key "PYTHON_VERSION")
            if [ -n "$pyver" ] && command -v uv &>/dev/null; then
                uv python uninstall "$pyver" 2>/dev/null || true
            fi
            ;;
        4)
            echo "  [Rollback] Removing virtual environment..."
            local vpath
            vpath=$(checkpoint_read_key "VENV_PATH")
            if [ -n "$vpath" ] && [ -d "$vpath" ]; then
                rm -rf "$vpath"
                echo "  Removed $vpath"
            fi
            checkpoint_write_key "STAGE_4_GROUPS_DONE" ""
            ;;
        5)
            echo "  [Rollback] Removing NVM directory..."
            local nvm_dir="${NVM_DIR:-$HOME/.nvm}"
            if [ -d "$nvm_dir" ]; then
                rm -rf "$nvm_dir"
                echo "  Removed $nvm_dir"
            fi
            ;;
        6)
            echo "  [Rollback] Removing SDKMAN directory..."
            local sdk_dir="${SDKMAN_DIR:-$HOME/.sdkman}"
            if [ -d "$sdk_dir" ]; then
                rm -rf "$sdk_dir"
                echo "  Removed $sdk_dir"
            fi
            ;;
        7)
            echo "  [Rollback] Restoring shell RC files from backup..."
            _restore_rc_backup "$HOME/.bashrc"
            _restore_rc_backup "$HOME/.zshrc"
            ;;
        *)
            echo "  [Rollback] Unknown stage $n, nothing to do."
            ;;
    esac
}

# --- Shell RC backup/restore ---

# Backup a single RC file before modification.
backup_shell_rc() {
    local rc_file="$1"
    if [ -f "$rc_file" ]; then
        mkdir -p "$CHECKPOINT_BACKUP_DIR"
        local base_name ts backup_path
        base_name=$(basename "$rc_file")
        ts=$(date +%Y%m%d_%H%M%S)
        backup_path="$CHECKPOINT_BACKUP_DIR/${base_name}.${ts}"
        cp "$rc_file" "$backup_path"
        # Also keep a "latest" symlink for easy restore
        ln -sf "$backup_path" "$CHECKPOINT_BACKUP_DIR/${base_name}.latest"
    fi
}

# Restore RC file from latest backup.
_restore_rc_backup() {
    local rc_file="$1"
    local base_name latest
    base_name=$(basename "$rc_file")
    latest="$CHECKPOINT_BACKUP_DIR/${base_name}.latest"
    if [ -L "$latest" ] && [ -f "$latest" ]; then
        cp "$(readlink -f "$latest" 2>/dev/null || readlink "$latest")" "$rc_file"
        echo "  Restored $rc_file from backup"
    fi
}

# --- ERR trap ---

# Set up ERR trap for a given stage.
# Usage: checkpoint_trap_setup 3 VENV
# The trap fires on any command failure (due to set -e).
checkpoint_trap_setup() {
    local n="$1" name="$2"
    trap "checkpoint_fail_stage $n $name; exit 1" ERR
}

# Clear the ERR trap (call after stage completes successfully).
checkpoint_trap_clear() {
    trap - ERR
}

# --- Resume menu ---

# Show resume menu when previous failed/in_progress state is detected.
# Returns via global: RESUME_ACTION (resume|reset|from_N)
RESUME_ACTION=""
checkpoint_show_resume_menu() {
    local has_failure=false
    local failed_stage=""
    local last_done=0

    for n in 1 2 3 4 5 6 7; do
        local name
        name=$(_stage_name "$n")
        local state
        state=$(checkpoint_get_state "$n" "$name")
        case "$state" in
            done|skipped) last_done=$n ;;
            failed|in_progress)
                has_failure=true
                failed_stage=$n
                break
                ;;
        esac
    done

    if [ "$has_failure" = false ] && [ "$last_done" -lt 7 ] && [ "$last_done" -gt 0 ]; then
        # Partially complete, not failed — treat as resumable
        has_failure=true
        failed_stage=$((last_done + 1))
    fi

    if [ "$has_failure" = false ] && [ "$last_done" -eq 0 ]; then
        # Fresh install
        RESUME_ACTION="reset"
        return
    fi

    if [ "$has_failure" = false ]; then
        # All done
        echo ""
        echo "  Previous installation completed successfully."
        echo "  Options:"
        echo "    1) Reinstall from scratch"
        echo "    2) Cancel"
        local choice
        read -rp "  Choice [2]: " choice
        case "${choice:-2}" in
            1) RESUME_ACTION="reset" ;;
            *) RESUME_ACTION="cancel" ;;
        esac
        return
    fi

    echo ""
    echo "  Previous installation detected (failed/incomplete at stage $failed_stage)."
    echo "  Completed stages: $last_done/7"
    echo ""
    echo "  Options:"
    echo "    1) Resume — skip completed stages, continue from stage $failed_stage"
    echo "    2) Reset  — start from scratch"
    echo "    3) Cancel"
    local choice
    read -rp "  Choice [1]: " choice
    case "${choice:-1}" in
        1) RESUME_ACTION="resume" ;;
        2) RESUME_ACTION="reset" ;;
        *) RESUME_ACTION="cancel" ;;
    esac
}

# Reset state file for fresh install.
checkpoint_reset() {
    rm -f "$CHECKPOINT_STATE"
    checkpoint_init
}

# --- Internal helpers ---

# Map stage number to state key name.
_stage_name() {
    case "$1" in
        1) echo "HARDWARE" ;;
        2) echo "NVIDIA" ;;
        3) echo "PYTHON" ;;
        4) echo "VENV" ;;
        5) echo "NODE" ;;
        6) echo "JAVA" ;;
        7) echo "SHELL" ;;
        *) echo "UNKNOWN" ;;
    esac
}
